### ISSUE TITLE
final rubric

### ISSUE THREAD

**Issue by Sara-Samer** [devkhedr/udemy-website#2]
- [x]  the courses data is fetched only once when the app start
- [x]  clicking on any course’s card opens the course’s page
- [x]  the ui design looks exactly as the attached screenshots.
- [x]  loading spinner is shown while the courses are being fetched
- [x]  the search function works as described.

**Comment by Sara-Samer** [comment]
code is clean and you made a nice folder structure and good refactoring. but you didn't meet with what was requested from this assignment

**Comment by Mohammed-Khedr** [comment]
Done now.
